"""Image generation capability interface."""

from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Any

from pydantic import BaseModel, Field


class GeneratedImage(BaseModel):
    """An image generated by an image generation adapter."""

    data: bytes | None = None
    url: str | None = None
    format: str = "png"


class ImageGenRequest(BaseModel):
    """Request model for image generation."""

    prompt: str
    negative_prompt: str | None = None
    width: int = 1024
    height: int = 1024
    quality: str = "standard"
    num_images: int = 1
    extra: dict[str, Any] = Field(default_factory=dict)


class ImageGenResponse(BaseModel):
    """Response model for image generation."""

    images: list[GeneratedImage]
    model: str


class ImageGenerationInterface(ABC):
    """Abstract interface for image generation adapters."""

    @abstractmethod
    async def generate_image(self, request: ImageGenRequest) -> ImageGenResponse:
        """Generate one or more images from a prompt."""
        ...
